Rework Demo Application
MindscapeHQ/raygun4reactnative pull request #32
Opened 2021-01-29 00:38 UTC by raygun-harrison

This PR updates the demo application such that all factors of the Raygun4ReactNative provider can be tested

2021-01-31 21:39 UTC, mduncan26 requested changes

2021-01-31 21:39 UTC, mduncan26 commented on demo/screens/Home.tsx
> +  apiKey: 'XyNxA6gLQrBOYYcsZc0A',// Your API key
Should remove this before merging

2021-01-31 23:59 UTC, raygun-harrison commented on demo/screens/Home.tsx
> +  apiKey: 'XyNxA6gLQrBOYYcsZc0A',// Your API key
ahhh dammit hahah

2021-02-01 00:02 UTC, raygun-harrison commented on demo/screens/Home.tsx
> +  apiKey: 'XyNxA6gLQrBOYYcsZc0A',// Your API key
all done

2021-02-01 00:16 UTC, mduncan26 approved these changes

2021-02-01 00:19 UTC, merged